services:
  backend:
    build: ./backend
    container_name: ravy_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    extra_hosts:
      - "aws-1-eu-north-1.pooler.supabase.com:13.60.102.132"
    networks:
      - ravy_network

networks:
  ravy_network:
    driver: bridge
